<?php
// coupons-array.php
// بيانات تجريبية للكوبونات
$coupons = [
    1 => [
        'code' => 'WELCOME10',
        'description' => '10% off for new customers',
        'discount_type' => 'percentage',
        'discount_value' => 10,
        'min_order' => 0,
        'max_discount' => 50,
        'usage_limit' => 100,
        'used_count' => 45,
        'start_date' => '2024-01-01',
        'expiry_date' => '2024-12-31',
        'status' => 'active',
        'applicable_products' => 'all',
        'applicable_categories' => 'all'
    ],
    2 => [
        'code' => 'SUMMER20',
        'description' => '20% off summer collection',
        'discount_type' => 'percentage',
        'discount_value' => 20,
        'min_order' => 50,
        'max_discount' => 100,
        'usage_limit' => 50,
        'used_count' => 23,
        'start_date' => '2024-06-01',
        'expiry_date' => '2024-08-31',
        'status' => 'scheduled',
        'applicable_products' => 'specific',
        'applicable_categories' => 'summer'
    ],
    3 => [
        'code' => 'FLASH15',
        'description' => '15% off flash sale',
        'discount_type' => 'percentage',
        'discount_value' => 15,
        'min_order' => 30,
        'max_discount' => 75,
        'usage_limit' => 200,
        'used_count' => 189,
        'start_date' => '2024-03-10',
        'expiry_date' => '2024-03-20',
        'status' => 'active',
        'applicable_products' => 'all',
        'applicable_categories' => 'all'
    ],
    4 => [
        'code' => 'FIXED25',
        'description' => '$25 off on orders over $100',
        'discount_type' => 'fixed',
        'discount_value' => 25,
        'min_order' => 100,
        'max_discount' => 25,
        'usage_limit' => 30,
        'used_count' => 12,
        'start_date' => '2024-02-01',
        'expiry_date' => '2024-04-30',
        'status' => 'active',
        'applicable_products' => 'all',
        'applicable_categories' => 'all'
    ],
    5 => [
        'code' => 'FREESHIP',
        'description' => 'Free shipping on all orders',
        'discount_type' => 'shipping',
        'discount_value' => 0,
        'min_order' => 25,
        'max_discount' => 0,
        'usage_limit' => 500,
        'used_count' => 312,
        'start_date' => '2024-01-15',
        'expiry_date' => '2024-12-31',
        'status' => 'active',
        'applicable_products' => 'all',
        'applicable_categories' => 'all'
    ],
    6 => [
        'code' => 'EXPIRED10',
        'description' => '10% off expired coupon',
        'discount_type' => 'percentage',
        'discount_value' => 10,
        'min_order' => 0,
        'max_discount' => 30,
        'usage_limit' => 100,
        'used_count' => 98,
        'start_date' => '2023-01-01',
        'expiry_date' => '2023-12-31',
        'status' => 'expired',
        'applicable_products' => 'all',
        'applicable_categories' => 'all'
    ],
    7 => [
        'code' => 'VIP50',
        'description' => '50% off for VIP members',
        'discount_type' => 'percentage',
        'discount_value' => 50,
        'min_order' => 200,
        'max_discount' => 200,
        'usage_limit' => 10,
        'used_count' => 4,
        'start_date' => '2024-03-01',
        'expiry_date' => '2024-06-30',
        'status' => 'active',
        'applicable_products' => 'specific',
        'applicable_categories' => 'premium'
    ]
];
?>